# Toolchain configuration for clang/llvm

# SET(CMAKE_C_COMPILER clang)
# SET(CMAKE_CXX_COMPILER clang++)
SET(CMAKE_C_COMPILER llvm-gcc)
SET(CMAKE_CXX_COMPILER llvm-g++)


# SET(CMAKE_TOOLCHAIN_PREFIX llvm-)

# SET(CMAKE_AR "/usr/bin/llvm-ar --plugin libLLVMgold.so" CACHE FILEPATH "llvm ar")
SET(CMAKE_AR "/usr/bin/llvm-ar" CACHE FILEPATH "llvm ar")
SET(CMAKE_LINKER "/usr/bin/llvm-ld" CACHE FILEPATH "llvm ld")
SET(CMAKE_NM "/usr/bin/llvm-nm" CACHE FILEPATH "llvm nm")
SET(CMAKE_OBJDUMP "/usr/bin/llvm-objdump" CACHE FILEPATH "llvm objdump")
# SET(CMAKE_RANLIB "/usr/bin/llvm-ranlib" CACHE FILEPATH "llvm ranlib")
SET(CMAKE_RANLIB "/bin/true" CACHE FILEPATH "llvm ranlib")

# SET (CMAKE_C_FLAGS "-std=c99" CACHE STRING "")
SET (CMAKE_C_FLAGS "" CACHE STRING "")
SET (CMAKE_C_FLAGS_DEBUG "-g" CACHE STRING "")
SET (CMAKE_C_FLAGS_MINSIZEREL "-Os -DNDEBUG" CACHE STRING "")
SET (CMAKE_C_FLAGS_RELEASE "-O4 -DNDEBUG" CACHE STRING "")
SET (CMAKE_C_FLAGS_RELWITHDEBINFO "-O2 -g" CACHE STRING "")

# SET (CMAKE_CXX_FLAGS "-Wall" CACHE STRING "")
SET (CMAKE_CXX_FLAGS "" CACHE STRING "")
SET (CMAKE_CXX_FLAGS_DEBUG "-g" CACHE STRING "")
SET (CMAKE_CXX_FLAGS_MINSIZEREL "-Os -DNDEBUG" CACHE STRING "")
# Requires llvm-dev and binutils-gold
# SET (CMAKE_CXX_FLAGS_RELEASE "-use-gold-plugin -O4 -DNDEBUG" CACHE STRING "")
SET (CMAKE_CXX_FLAGS_RELEASE "-O4 -DNDEBUG" CACHE STRING "")
SET (CMAKE_CXX_FLAGS_RELWITHDEBINFO "-O2 -g" CACHE STRING "")


