
MACRO(ADD_SMIL_LIBRARY _LIB_NAME _LIB_DEPS)

	SET(LIB_NAME ${SMIL_LIB_PREFIX}${_LIB_NAME})
	SET(LIB_DEPS ${SMIL_EXT_DEPS} ${_LIB_DEPS})
		
	FILE(GLOB LIB_SRCS src/*.cpp)
	IF(LIB_SRCS)
		ADD_LIBRARY(${LIB_NAME} ${LIB_SRCS})
		TARGET_LINK_LIBRARIES(${LIB_NAME} ${LIB_DEPS}) #gomp pthread)
		LIST(APPEND LIB_DEPS ${LIB_NAME})
		SET(SMIL_LIBS ${SMIL_LIBS} ${LIB_NAME} PARENT_SCOPE)
# message(${SMIL_LIBS})
	ENDIF(LIB_SRCS)


	IF(WRAP_PYTHON)
	      IF(SWIG_FOUND AND PYTHONLIBS_FOUND)
		  SET(PYTHON_LIB_NAME ${LIB_NAME}Python)
		  SET(SWIG_INTERFACE_FILES ${SWIG_INTERFACE_FILES} ${PYTHON_LIB_NAME}.i PARENT_SCOPE)
		  SET_SOURCE_FILES_PROPERTIES(${PYTHON_LIB_NAME}.i PROPERTIES CPLUSPLUS ON)
		  
# 		  IF(USE_QT)
# 		      SET(CMAKE_SWIG_FLAGS -DUSE_QT)
# 		  ENDIF(USE_QT)

# 		  SWIG_ADD_MODULE(smilPython python ${PYTHON_LIB_NAME}.i)
# 		  
# 	# 	  SWIG_ADD_MODULE(smilCoreJava java smilCore.i)
# 		  SWIG_LINK_LIBRARIES(smilPython ${LIB_DEPS} ${PYTHON_LIBRARIES})
# 		  IF(USE_QT)
# 	# 	      SWIG_LINK_LIBRARIES(smilCorePython smilCoreGui)
# 		  ENDIF(USE_QT)
# 	# 	  SWIG_LINK_LIBRARIES(smilCoreJava smilCore)
# 		  
# 		  SET_TARGET_PROPERTIES(_smilPython PROPERTIES LINKER_LANGUAGE CXX)
	#  	  SET_TARGET_PROPERTIES(smilCoreJava PROPERTIES LINKER_LANGUAGE CXX)

	      ENDIF(SWIG_FOUND AND PYTHONLIBS_FOUND)


	ENDIF(WRAP_PYTHON)
	
	
	IF(BUILD_TEST)
		FILE(GLOB TEST_SRCS RELATIVE ${CMAKE_CURRENT_SOURCE_DIR}  test/*.cpp)
		
		IF(TEST_SRCS)
			FOREACH(_SRC ${TEST_SRCS})
				STRING(REPLACE ".cpp" "" TEST_EXE_NAME ${_SRC})
				STRING(REPLACE "test/" "" TEST_EXE_NAME ${TEST_EXE_NAME})
				ADD_EXECUTABLE(${TEST_EXE_NAME} ${_SRC})
				TARGET_LINK_LIBRARIES(${TEST_EXE_NAME} ${LIB_DEPS})
				ADD_TEST("${_MOD}_${TEST_EXE_NAME}" ${EXECUTABLE_OUTPUT_PATH}/${TEST_EXE_NAME})
			ENDFOREACH(_SRC ${TEST_SOURCE_FILES})
		ENDIF(TEST_SRCS)
	ENDIF(BUILD_TEST)
	
ENDMACRO(ADD_SMIL_LIBRARY _LIB_NAME _LIB_DEPS)
