name: nonreg-tests_windows-latest

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        py: [
          "3.9",
          "3.10",
          "3.11",
          "3.12",
          "3.13",
        ]
    env:
      QT_QPA_PLATFORM: offscreen

    steps:
      - uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.9.0
        with:
          run-install: false

      - name: Install dependencies
        run: |
          pixi init
          pixi add python==${{ matrix.py }}
          pixi add swig freetype libpng libtiff zlib libcurl qwt numpy

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9

      - name: Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2

      - name: Create & configure Smil build directory
        run: |
          mkdir build && cd build
          export CMAKE_PREFIX_PATH="$CONDA_PREFIX/Library"
          cmake \
            -DCMAKE_COMPILE_WARNING_AS_ERROR=ON \
            -DBUILD_TEST=ON \
            -DWRAP_PYTHON=ON \
            -DUSE_NUMPY=ON \
            $GITHUB_WORKSPACE
        shell: pixi run bash -e {0}
        env:
          CMAKE_GENERATOR: Ninja
          CMAKE_BUILD_TYPE: Release
          CMAKE_CC_COMPILER_LAUNCHER: sccache
          CMAKE_CXX_COMPILER_LAUNCHER: sccache
          SCCACHE_GHA_ENABLED: "true"

      - name: Build Smil
        run: |
          cd build
          cmake --build . --config Release

      - name: Install Smil
        run: |
          cd build
          cmake --build . --config Release --target install

      - name: Execute non-regression tests and benchmarks
        run: |
          cd build
          ctest -C Release -LE "python"
        shell: pixi run bash -e {0}

      - name: Execute Python tests
        continue-on-error: true
        run: |
          cd build
          ctest -C Release -L python --output-on-failure
        shell: pixi run bash -e {0}
        env:
          PYTHONPATH: "/c/Program Files (x86)/Smil/lib:/c/Program Files (x86)/Smil/lib/smilPython"
